apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: app-wordpress
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/nfsdata/wordpress/mariadb
    server: k8s-node2