kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pvc
  namespace: app-wordpress
spec:
  selector:
    matchLabels:
      app-wordpress: mariadb-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
#ceph
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: app-wordpress
  labels:
    app-wordpress: mariadb-pv  
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 172.16.16.10
    path: /app-wordpress/mariadb
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
