---
# ceph
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: app-wordpress
  labels:
    app-wordpress: wordpress-pv  
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 172.16.16.10
    path: /app-wordpress/wordpress
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-pvc
  namespace: app-wordpress
spec:
  selector:
    matchLabels:
      app-wordpress: wordpress-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi