apiVersion: v1
kind: PersistentVolume
metadata:
  name: iomsmq-pv
  namespace: gwhospital
  labels:
    pv: iomsmq-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
      - 172.16.16.10
    path: /gwhospital/12iomsmq/data
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iomsmq-pvc
  namespace: gwhospital
spec:
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels:
      pv: iomsmq-pv
  resources:
    requests:
      storage: 20Gi