apiVersion: v1
kind: PersistentVolume
metadata:
  name: iomsmq-pv
  namespace: gwhospital
  labels:
    pv: iomsmq-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/gwhospital/12iomsmq/data
    server: k8s-node3