apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-storage-mariadb-pv
  namespace: app-storage
  labels:
    app-storage: mariadb-pv  
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
      - 172.16.16.10
    path: /app-storage/mariadb
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pvc
  namespace: app-storage
spec:
  selector:
    matchLabels:
      app-storage: mariadb-pv 
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi