apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-storage-storage-pv
  namespace: app-storage
  labels:
    app-storage: storage-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 512Gi
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
      - 172.16.16.10
    path: /app-storage/storage
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false