apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  namespace: app-nextcloud
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/nfsdata/nextcloud/nextcloud
    server: k8s-node2