apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-storage-storage-pv
  namespace: app-storage
  labels:
    app-storage: storage-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 512Gi
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
      - 172.16.16.10
    path: /app-storage/storage
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-pvc
  namespace: app-storage
spec:
  selector:
    matchLabels:
      app-storage: storage-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Gi