---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-pvc
  namespace: app-storage
spec:
  selector:
    matchLabels:
      app-storage: storage-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
---
apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: app-storage
spec:
  ports:
  - port: 80
  selector:
    app: storage
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: storage
  namespace: app-storage
spec:
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - image: arm64v8/nextcloud:13
        name: storage
#        env:
#        - name: MYSQL_ROOT_PASSWORD
#          value: password
        ports:
        - containerPort: 80
          name: storage
        volumeMounts:
        - name: storage-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: storage-persistent-storage
        persistentVolumeClaim:
          claimName: storage-pvc 

