
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: gwhospital
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: mysql
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: gwhospital
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
 #     - image: kylin_base_mysql:5.6.28
      - image: arm64v8/mariadb:10
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-workdir
          mountPath: /var/lib/mysql
        - name: mysql-localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: mysql-timezone
          mountPath: /etc/timezone     
          readOnly: true
      volumes:
      - hostPath:
          path: /etc/localtime
        name: mysql-localtime
      - hostPath:
          path: /etc/timezone
        name: mysql-timezone
      - name: mysql-workdir
        persistentVolumeClaim:
          claimName: mysql-pvc

