apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: gwhospital
  labels:
    pv: mysql-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
      - 172.16.16.10
    path: /data/gwhospital/08mysql/mysql
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
  namespace: gwhospital
spec:
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels:
      pv: mysql-pv
  resources:
    requests:
      storage: 20Gi