apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: gwhospital
  labels:
    pv: mysql-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/gwhospital/08mysql/mysql
    server: k8s-node3