apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: gwhospital
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/gwhospital/06redis/redis
    server: k8s-node3