apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: app-adminer
spec:
  ports:
  - port: 8080
  selector:
    app: adminer
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: adminer
  namespace: app-adminer
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - image: adminer
        name: adminer
        ports:
        - containerPort: 8080
          name: adminer
