apiVersion: v1
kind: PersistentVolume
metadata:
  name: svn-pv
  namespace: gwhospital
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/gwhospital/02svn/svn
    server: k8s-node3