apiVersion: v1
kind: PersistentVolume
metadata:
  name: ui-pv
  namespace: gwhospital
  labels:
    pv: ui-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/gwhospital/13ui/www
    server: k8s-node3