apiVersion: v1
kind: PersistentVolume
metadata:
  name: discovery-pv
  namespace: gwhospital
  labels:
    pv: discovery-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/gwhospital/03discovery/data
    server: k8s-node3