apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastdfs-pv
  namespace: gwhospital
  labels:
    pv: fastdfs-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
      - k8s-master
    path: /gwhospital/05fastdfs/fastdfs
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fastdfs-pvc
  namespace: gwhospital
spec:
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels:
      pv: fastdfs-pv
  resources:
    requests:
      storage: 50Gi