apiVersion: v1
kind: PersistentVolume
metadata:
  name: fastdfs-pv
  namespace: gwhospital
  labels:
    pv: fastdfs-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/gwhospital/05fastdfs/fastdfs
    server: k8s-node3