apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  namespace: gwhospital
  labels:
    pv: rabbitmq-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  cephfs:
    monitors:
      - 172.16.16.10
    path: /gwhospital/01rabbitmq/mnesia
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-pvc
  namespace: gwhospital
spec:
  accessModes:
  - ReadWriteMany
  selector:
    matchLabels:
      pv: rabbitmq-pv
  resources:
    requests:
      storage: 20Gi