apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  namespace: gwhospital
  labels:
    pv: rabbitmq-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /data/gwhospital/01rabbitmq/rabbitmq
    server: k8s-node3